const data = [
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Контроль входной ф109х26мм",
            "operation.operation": "0005",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Данилова С. В.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-16T23:23:26+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000005",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 230.000000,
            "operation.modified_ts": "2020-01-10T14:07:36+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "STOL_108",
            "operation.plan.yield.secondary": 230.000000,
            "operation.act.first_logon_ts": "2020-01-16T23:23:25+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Данилова С. В.",
            "operation.act.workplace_default": "STOL_108",
            "operation.record_num": 1,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "STOL_MTZ",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Очистка дробеструйная ф109х26мм",
            "operation.operation": "0010",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Данилова С. В.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-16T23:23:44+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000010",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 230.000000,
            "operation.modified_ts": "2020-01-10T14:07:36+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "PROBLAST",
            "operation.plan.yield.secondary": 230.000000,
            "operation.act.first_logon_ts": "2020-01-16T23:23:43+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Данилова С. В.",
            "operation.act.workplace_default": "PROBLAST",
            "operation.record_num": 2,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "KOAEM",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Металлизация ф109х26мм",
            "operation.operation": "0015",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Данилова С. В.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-16T23:24:03+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000015",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 230.000000,
            "operation.modified_ts": "2020-01-10T14:07:36+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "METALL",
            "operation.plan.yield.secondary": 230.000000,
            "operation.act.first_logon_ts": "2020-01-16T23:24:02+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Данилова С. В.",
            "operation.act.workplace_default": "METALL",
            "operation.record_num": 3,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "KOAEM",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Меднение эл.химическое ф109х26мм",
            "operation.operation": "0020",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Данилова С. В.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-16T23:24:28+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000020",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 230.000000,
            "operation.modified_ts": "2020-01-10T14:07:37+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "MTZ108_1",
            "operation.plan.yield.secondary": 230.000000,
            "operation.act.first_logon_ts": "2020-01-16T23:24:27+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Данилова С. В.",
            "operation.act.workplace_default": "MTZ108_1",
            "operation.record_num": 4,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "MTZ_108",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Обмазка ф109х26мм",
            "operation.operation": "0030",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Данилова С. В.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-16T23:24:52+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000030",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 230.000000,
            "operation.modified_ts": "2020-01-10T14:07:38+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "OBMAZKA1",
            "operation.plan.yield.secondary": 230.000000,
            "operation.act.first_logon_ts": "2020-01-16T23:24:51+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Данилова С. В.",
            "operation.act.workplace_default": "OBMAZKA1",
            "operation.record_num": 5,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "OBMAZKA1",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Выдавливание ф109х26мм>ф49х24мм",
            "operation.operation": "0080",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Данилова С. В.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-16T23:25:14+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000080",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 218.040000,
            "operation.modified_ts": "2020-01-10T14:07:38+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "PA_8340",
            "operation.plan.yield.secondary": 218.040000,
            "operation.act.first_logon_ts": "2020-01-16T23:25:13+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Данилова С. В.",
            "operation.act.workplace_default": "PA_8340",
            "operation.record_num": 6,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "PA_8340",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Правка ф49,0х24,0мм",
            "operation.operation": "0090",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Данилова С. В.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-16T23:25:40+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000090",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 218.040000,
            "operation.modified_ts": "2020-01-10T14:07:38+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "PRAV400",
            "operation.plan.yield.secondary": 218.040000,
            "operation.act.first_logon_ts": "2020-01-16T23:25:39+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Данилова С. В.",
            "operation.act.workplace_default": "PRAV400",
            "operation.record_num": 7,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "PRAV400",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Очистка ф49,0х24,0мм",
            "operation.operation": "0095",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Третьякова А. В.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-17T14:19:07+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000095",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 218.040000,
            "operation.modified_ts": "2020-01-10T14:07:38+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "OBEZ_4",
            "operation.plan.yield.secondary": 218.040000,
            "operation.act.first_logon_ts": "2020-01-17T14:19:06+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Третьякова А. В.",
            "operation.act.workplace_default": "OBEZ_4",
            "operation.record_num": 8,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "OBEZ",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Удаление медного покрытия ф49х24мм",
            "operation.operation": "0100",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Третьякова А. В.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-17T14:19:27+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000100",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 218.040000,
            "operation.modified_ts": "2020-01-10T14:07:40+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "TRAV_3",
            "operation.plan.yield.secondary": 218.040000,
            "operation.act.first_logon_ts": "2020-01-17T14:19:26+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Третьякова А. В.",
            "operation.act.workplace_default": "TRAV_3",
            "operation.record_num": 9,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "TRAV",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Токарная ф48,0х26мм",
            "operation.operation": "0105",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Шарова Е. П.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-22T18:26:14+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000105",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 189.750000,
            "operation.modified_ts": "2020-01-10T14:07:40+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "1K62_1",
            "operation.plan.yield.secondary": 189.750000,
            "operation.act.first_logon_ts": "2020-01-22T18:26:13+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Шарова Е. П.",
            "operation.act.workplace_default": "1K62_1",
            "operation.record_num": 10,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "1K62_1",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Очистка пескоструйная ф48,0х26мм",
            "operation.operation": "0110",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Третьякова А. В.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-23T17:18:57+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000110",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 189.750000,
            "operation.modified_ts": "2020-01-10T14:07:40+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "PESOK_3",
            "operation.plan.yield.secondary": 189.750000,
            "operation.act.first_logon_ts": "2020-01-23T17:18:56+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Третьякова А. В.",
            "operation.act.workplace_default": "PESOK_3",
            "operation.record_num": 11,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "PESOK",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Очистка ф48,0х26мм",
            "operation.operation": "0115",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Третьякова А. В.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-23T17:19:18+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000115",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 189.750000,
            "operation.modified_ts": "2020-01-10T14:07:40+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "OBEZ_4",
            "operation.plan.yield.secondary": 189.750000,
            "operation.act.first_logon_ts": "2020-01-23T17:19:17+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Третьякова А. В.",
            "operation.act.workplace_default": "OBEZ_4",
            "operation.record_num": 12,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "OBEZ",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
    {
        "__rowType": "OBJECT",
        "__type": "U_Orders.operationList",
        "obj": {
            "operation.act.yield.tertiary": 0.000000,
            "operation.designation": "Травление ф48,0х26мм",
            "operation.operation": "0120",
            "operation.act.status.color": 32768,
            "operation.act.status.text": "Завершена",
            "operation.act.predecessor_status": "E",
            "operation.person_end": "Третьякова А. В.",
            "operation.plan.yield.primary": 23.000000,
            "operation.userfield66": null,
            "operation.has_inspection": false,
            "operation.act.last_logoff_ts": "2020-01-23T17:19:40+04:00",
            "operation.number_of_splits": null,
            "operation.modified_by": "SVDanilova",
            "operation.act.scrap.secondary": 0.000000,
            "operation.processing_code": "SYSTEM",
            "operation.act.scrap.tertiary": 0.000000,
            "operation.act.total_duration": 1,
            "operation.is_replaceable": false,
            "order.salesorder": "5182-19-1-2",
            "operation.id": "P80-0120-00B0000120",
            "order.id": "P80-0120-00B",
            "operation.plan.total_duration": 0,
            "operation.person_control": "",
            "operation.comment_text": "",
            "operation.split_indicator": false,
            "operation.userfield35": null,
            "operation.act.yield.secondary": 189.750000,
            "operation.modified_ts": "2020-01-10T14:07:40+04:00",
            "operation.cycle.target": 0,
            "operation.plan.start_ts": null,
            "order.route": "AR80-0000323",
            "operation.ls_safo_nr": null,
            "operation.splitting_authorization": "N",
            "operation.act.workplace": "TRAV_1",
            "operation.plan.yield.secondary": 189.750000,
            "operation.act.first_logon_ts": "2020-01-23T17:19:39+04:00",
            "operation.active": true,
            "operation.act.yield.primary": 23.000000,
            "operation.userfield01": null,
            "operation.person_start": "Третьякова А. В.",
            "operation.act.workplace_default": "TRAV_1",
            "operation.record_num": 13,
            "operation.max_number_of_split": 0,
            "operation.act.scrap.primary": 0.000000,
            "operation.sequence": "000",
            "inspectionstep.number": 0,
            "operation.act.status.textnumber": 50,
            "operation.workplace_group": "TRAV",
            "operation.status_color": "#008700",
            "operation.act.rework.primary": 0.000000,
            "operation.act.status": "E"
        }
    },
]

export default data 